"""MCP wrappers — domain: visuals."""

from __future__ import annotations

from tools import (
    pbi_add_area_chart_tool,
    pbi_add_bar_chart_tool,
    pbi_add_card_tool,
    pbi_add_clustered_column_chart_tool,
    pbi_add_combo_chart_tool,
    pbi_add_conditional_formatting_tool,
    pbi_add_donut_chart_tool,
    pbi_add_funnel_tool,
    pbi_add_gauge_tool,
    pbi_add_hundred_percent_stacked_area_chart_tool,
    pbi_add_hundred_percent_stacked_bar_chart_tool,
    pbi_add_hundred_percent_stacked_column_chart_tool,
    pbi_add_kpi_tool,
    pbi_add_labelled_card_tool,
    pbi_add_line_chart_tool,
    pbi_add_map_tool,
    pbi_add_matrix_tool,
    pbi_add_multi_row_card_tool,
    pbi_add_pie_chart_tool,
    pbi_add_ribbon_chart_tool,
    pbi_add_scatter_chart_tool,
    pbi_add_slicer_tool,
    pbi_add_stacked_area_chart_tool,
    pbi_add_stacked_bar_chart_tool,
    pbi_add_stacked_column_chart_tool,
    pbi_add_table_visual_tool,
    pbi_add_text_box_tool,
    pbi_add_treemap_tool,
    pbi_add_visual_tool,
    pbi_add_waterfall_tool,
    pbi_apply_design_tool,
    pbi_apply_theme_tool,
    pbi_auto_grid_layout_tool,
    pbi_build_dashboard_tool,
    pbi_compile_report_tool,
    pbi_convert_visual_type_tool,
    pbi_create_page_tool,
    pbi_delete_page_tool,
    pbi_describe_page_tool,
    pbi_diagnose_render_risks_tool,
    pbi_disable_card_autoscale_tool,
    pbi_export_active_theme_tool,
    pbi_extract_report_tool,
    pbi_get_page_tool,
    pbi_list_pages_tool,
    pbi_move_visual_tool,
    pbi_patch_layout_tool,
    pbi_remove_visual_tool,
    pbi_repair_report_fields_tool,
    pbi_set_page_size_tool,
    pbi_set_series_color_tool,
    pbi_set_visual_format_property_tool,
    pbi_update_visual_bindings_tool,
    pbi_validate_report_fields_tool,
    pbi_validate_theme_tool,
)

from ._helpers import register_tool

register_tool(pbi_extract_report_tool)
register_tool(pbi_compile_report_tool)
register_tool(pbi_patch_layout_tool)
register_tool(pbi_list_pages_tool)
register_tool(pbi_validate_report_fields_tool)
register_tool(pbi_repair_report_fields_tool)
register_tool(pbi_diagnose_render_risks_tool)
register_tool(pbi_get_page_tool)
register_tool(pbi_convert_visual_type_tool)
register_tool(pbi_auto_grid_layout_tool)
register_tool(pbi_describe_page_tool)
register_tool(pbi_create_page_tool)
register_tool(pbi_delete_page_tool)
register_tool(pbi_set_page_size_tool)
register_tool(pbi_add_card_tool)
register_tool(pbi_add_bar_chart_tool)
register_tool(pbi_add_clustered_column_chart_tool)
register_tool(pbi_add_stacked_bar_chart_tool)
register_tool(pbi_add_stacked_column_chart_tool)
register_tool(pbi_add_hundred_percent_stacked_bar_chart_tool)
register_tool(pbi_add_hundred_percent_stacked_column_chart_tool)
register_tool(pbi_add_ribbon_chart_tool)
register_tool(pbi_add_line_chart_tool)
register_tool(pbi_add_area_chart_tool)
register_tool(pbi_add_stacked_area_chart_tool)
register_tool(pbi_add_hundred_percent_stacked_area_chart_tool)
register_tool(pbi_add_donut_chart_tool)
register_tool(pbi_add_pie_chart_tool)
register_tool(pbi_add_treemap_tool)
register_tool(pbi_add_funnel_tool)
register_tool(pbi_add_multi_row_card_tool)
register_tool(pbi_add_table_visual_tool)
register_tool(pbi_add_scatter_chart_tool)
register_tool(pbi_add_combo_chart_tool)
register_tool(pbi_add_kpi_tool)
register_tool(pbi_add_map_tool)
register_tool(pbi_add_matrix_tool)
register_tool(pbi_add_waterfall_tool)
register_tool(pbi_add_slicer_tool)
register_tool(pbi_add_gauge_tool)
register_tool(pbi_add_labelled_card_tool)
register_tool(pbi_add_text_box_tool)
register_tool(pbi_remove_visual_tool)
register_tool(pbi_move_visual_tool)
register_tool(pbi_update_visual_bindings_tool)
register_tool(pbi_set_visual_format_property_tool)
register_tool(pbi_set_series_color_tool)
register_tool(pbi_add_conditional_formatting_tool)
register_tool(pbi_disable_card_autoscale_tool)
register_tool(pbi_apply_theme_tool)
register_tool(pbi_validate_theme_tool)
register_tool(pbi_export_active_theme_tool)
register_tool(pbi_apply_design_tool)
register_tool(pbi_add_visual_tool)
register_tool(pbi_build_dashboard_tool)
